# Use an official Python runtime as a parent image
FROM node:carbon


# Set the working directory to /app



WORKDIR /app
VOLUME /app

#COPY package*.json ./

RUN npm install


# Make port 80 available to the world outside this container
EXPOSE 8080
