kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hugo/PycharmProjects/AppProject/aioverlord-frontend"
